import { SerializedNodes } from '@craftjs/core';

export const facktree: SerializedNodes = {
  ROOT: {
    type: 'div',
    isCanvas: false,
    props: {
      className: 'flex flex-col items-center gap-10',
    },
    displayName: 'div',
    custom: {},
    hidden: false,
    nodes: ['jNSXg8S-i8', 'rRky9FKhnD', 'hfxgkIIx4y'],
    linkedNodes: {},
    parent: '',
  },
  '4GwOyEXtLh': {
    type: {
      resolvedName: 'Container',
    },
    isCanvas: true,
    props: {
      padding: [2],
      background: 'transparent',
      color: '#333333',
      borderRadius: 0,
      flexDirection: 'column',
      justifyContent: 'start',
      alignItems: 'start',
      width: '100%',
      height: 'auto',
      resizeable: false,
    },
    displayName: 'Container',
    custom: {
      toolbar: ['delete'],
      displayName: 'Container',
    },
    parent: 'jNSXg8S-i8',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  'jNSXg8S-i8': {
    type: {
      resolvedName: 'Container',
    },
    isCanvas: true,
    props: {
      padding: [44, 38, 44, 38],
      background: '#FFFFFF',
      color: '#333333',
      borderRadius: 0,
      flexDirection: 'column',
      justifyContent: 'start',
      alignItems: 'start',
      width: '100%',
      height: 'auto',
      shadow: 'md',
      resizeable: false,
      className: 'relative overflow-hidden ROOT !w-[210mm] mx-auto !h-[297mm]',
    },
    displayName: 'Container',
    custom: {
      toolbar: ['delete'],
      displayName: 'PAGE',
    },
    parent: 'ROOT',
    hidden: false,
    nodes: [
      'yx9zGQ3k4m',
      'GoorrL1vak',
      'p0jgczSeli',
      'dlk5aP94tJ',
      '4GwOyEXtLh',
      //   'uXkpkRM0Gl',
    ],
    linkedNodes: {},
  },
  yx9zGQ3k4m: {
    type: {
      resolvedName: 'Header',
    },
    isCanvas: false,
    props: {
      imageType: 'square',
      alignItems: 'center',
      margin: [0, 0, 6, 0],
      padding: [6, 12, 6, 12],
      justifyContent: 'center',
      image: {
        show: true,
        label: 'Image',
        value: 'Image',
      },
      title: {
        value: 'YOUR NAME',
        label: 'Title',
        show: true,
      },
      subtitle: {
        value: 'The role you are applying for?',
        label: 'SubTitle',
        show: true,
      },
      fields: [
        {
          value: 'Phone',
          label: 'Phone',
          show: true,
        },
        {
          value: 'Email',
          label: 'Email',
          show: true,
        },
        {
          value: 'LinkedIn/Portfolio',
          label: 'Link',
          show: true,
        },
        {
          value: 'Extra Link',
          label: 'Extra Link',
          show: false,
        },
        {
          value: 'Location',
          label: 'Location',
          show: true,
        },
        {
          value: 'Extra Field',
          label: 'Extra Field',
          show: false,
        },
      ],
    },
    displayName: 'Header',
    custom: {},
    parent: 'jNSXg8S-i8',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  GoorrL1vak: {
    type: {
      resolvedName: 'Summary',
    },
    isCanvas: true,
    props: {
      gap: '0px',
      margin: [0, 0, 6, 0],
      padding: [6, 12, 6, 12],
      entries: [
        {
          id: 'Entry 1',
          value: '',
        },
      ],
      title: 'Summary',
      placeholder:
        "What's the one thing that makes you the best candidate for this job?",
    },
    displayName: 'Summary',
    custom: {},
    parent: 'jNSXg8S-i8',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  dlk5aP94tJ: {
    type: {
      resolvedName: 'Experience',
    },
    isCanvas: true,
    props: {
      padding: [0],
      margin: [0, 0, 6, 0],
      gap: '0px',
      title: 'Experience',
    },
    displayName: 'Experience',
    custom: {
      toolbar: ['add', 'delete', 'setting'],
    },
    parent: 'jNSXg8S-i8',
    hidden: false,
    nodes: ['0AgVv3QnVq', 'IgqfuBodIr', 'HmUXRwLZZI', 'YxiU28dbQm'],
    linkedNodes: {},
  },
  HmUXRwLZZI: {
    type: {
      resolvedName: 'ExperienceEntry',
    },
    isCanvas: false,
    props: {
      entry: {
        id: 'Entry 1',
        value: '',
        companyDesc: '',
        companyName: '',
        datePeriod: '',
        location: '',
        title: '',
        hiddenField: [],
      },
      padding: [0, 12, 6, 12],
    },
    displayName: 'Experience Entry',
    custom: {
      toolbar: ['move', 'delete', 'setting'],
    },
    parent: 'dlk5aP94tJ',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  uXkpkRM0Gl: {
    type: {
      resolvedName: 'Education',
    },
    isCanvas: true,
    props: {
      padding: [0],
      margin: [0, 0, 6, 0],
      gap: '0px',
      deletable: true,
      title: 'Education',
    },
    displayName: 'Education',
    custom: {
      toolbar: ['add', 'delete', 'setting'],
    },
    // parent: 'jNSXg8S-i8',
    parent: 'rRky9FKhnD',
    hidden: false,
    nodes: [
      'Slx_mQX3AL',
      'YAeZas3Srk',
      'tEOle4fx78',
      '6vljunTenr',
      'TdpmHOvV7d',
    ],
    linkedNodes: {},
  },
  YAeZas3Srk: {
    type: {
      resolvedName: 'EducationEntry',
    },
    isCanvas: false,
    props: {
      entry: {
        id: 'Entry 1',
        value: '',
        location: '',
        schoolTitle: '',
        datePeriod: '',
        bullets: '',
        gpa: '--',
        hiddenField: ['gpa', 'location', 'bullets'],
      },
      deletable: true,
      padding: [0, 12, 6, 12],
    },
    displayName: 'Education Entry',
    custom: {
      toolbar: ['move', 'delete', 'setting'],
    },
    parent: 'uXkpkRM0Gl',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  '0AgVv3QnVq': {
    type: {
      resolvedName: 'ExperienceEntry',
    },
    isCanvas: false,
    props: {
      entry: {
        id: 'Entry 1',
        value: '',
        companyDesc: '',
        companyName: '',
        datePeriod: '',
        location: '',
        title: '',
        hiddenField: [],
      },
      deletable: true,
      padding: [0, 12, 6, 12],
    },
    displayName: 'Experience Entry',
    custom: {
      toolbar: ['move', 'delete', 'setting'],
    },
    parent: 'dlk5aP94tJ',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  IgqfuBodIr: {
    type: {
      resolvedName: 'ExperienceEntry',
    },
    isCanvas: false,
    props: {
      entry: {
        id: 'Entry 1',
        value: '',
        companyDesc: '',
        companyName: '',
        datePeriod: '',
        location: '',
        title: '',
        hiddenField: [],
      },
      deletable: true,
      padding: [0, 12, 6, 12],
    },
    displayName: 'Experience Entry',
    custom: {
      toolbar: ['move', 'delete', 'setting'],
    },
    parent: 'dlk5aP94tJ',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  p0jgczSeli: {
    type: {
      resolvedName: 'ExperienceEntry',
    },
    isCanvas: false,
    props: {
      entry: {
        id: 'Entry 1',
        value: '',
        companyDesc: '',
        companyName: '',
        datePeriod: '',
        location: '',
        title: '',
        hiddenField: [],
      },
      deletable: true,
      padding: [0, 12, 6, 12],
    },
    displayName: 'Experience Entry',
    custom: {
      toolbar: ['move', 'delete', 'setting'],
    },
    parent: 'jNSXg8S-i8',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  YxiU28dbQm: {
    type: {
      resolvedName: 'ExperienceEntry',
    },
    isCanvas: false,
    props: {
      entry: {
        id: 'Entry 1',
        value: '',
        companyDesc: '',
        companyName: '',
        datePeriod: '',
        location: '',
        title: '',
        hiddenField: [],
      },
      deletable: true,
      padding: [0, 12, 6, 12],
    },
    displayName: 'Experience Entry',
    custom: {
      toolbar: ['move', 'delete', 'setting'],
    },
    parent: 'dlk5aP94tJ',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  tEOle4fx78: {
    type: {
      resolvedName: 'EducationEntry',
    },
    isCanvas: false,
    props: {
      entry: {
        id: 'Entry 1',
        value: '',
        location: '',
        schoolTitle: '',
        datePeriod: '',
        bullets: '',
        gpa: '--',
        hiddenField: ['gpa', 'location', 'bullets'],
      },
      deletable: true,
      padding: [0, 12, 6, 12],
    },
    displayName: 'Education Entry',
    custom: {
      toolbar: ['move', 'delete', 'setting'],
    },
    parent: 'uXkpkRM0Gl',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  '6vljunTenr': {
    type: {
      resolvedName: 'EducationEntry',
    },
    isCanvas: false,
    props: {
      entry: {
        id: 'Entry 1',
        value: '',
        location: '',
        schoolTitle: '',
        datePeriod: '',
        bullets: '',
        gpa: '--',
        hiddenField: ['gpa', 'location', 'bullets'],
      },
      deletable: true,
      padding: [0, 12, 6, 12],
    },
    displayName: 'Education Entry',
    custom: {
      toolbar: ['move', 'delete', 'setting'],
    },
    parent: 'uXkpkRM0Gl',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  Slx_mQX3AL: {
    type: {
      resolvedName: 'EducationEntry',
    },
    isCanvas: false,
    props: {
      entry: {
        id: 'Entry 1',
        value: '',
        location: '',
        schoolTitle: '',
        datePeriod: '',
        bullets: '',
        gpa: '--',
        hiddenField: ['gpa', 'location', 'bullets'],
      },
      deletable: true,
      padding: [0, 12, 6, 12],
    },
    displayName: 'Education Entry',
    custom: {
      toolbar: ['move', 'delete', 'setting'],
    },
    parent: 'uXkpkRM0Gl',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  TdpmHOvV7d: {
    type: {
      resolvedName: 'EducationEntry',
    },
    isCanvas: false,
    props: {
      entry: {
        id: 'Entry 1',
        value: '',
        location: '',
        schoolTitle: '',
        datePeriod: '',
        bullets: '',
        gpa: '--',
        hiddenField: ['gpa', 'location', 'bullets'],
      },
      deletable: true,
      padding: [0, 12, 6, 12],
    },
    displayName: 'Education Entry',
    custom: {
      toolbar: ['move', 'delete', 'setting'],
    },
    parent: 'uXkpkRM0Gl',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  rRky9FKhnD: {
    type: {
      resolvedName: 'Container',
    },
    isCanvas: true,
    props: {
      padding: [44, 38, 44, 38],
      background: '#FFFFFF',
      color: '#333333',
      borderRadius: 0,
      flexDirection: 'column',
      justifyContent: 'start',
      alignItems: 'start',
      width: '100%',
      height: 'auto',
      shadow: 'md',
      resizeable: false,
      className: 'relative overflow-hidden ROOT !w-[210mm] mx-auto !h-[297mm]',
    },
    displayName: 'Container',
    custom: {
      toolbar: ['delete'],
      displayName: 'PAGE',
    },
    parent: 'ROOT',
    hidden: false,
    nodes: [
      //TODO:
      'uXkpkRM0Gl',
      'jh2NaWuv3f',
      'ThQeX6ezUI',
      'N_oK1Q69Z8',
      'dbZ6MwyAiv',
      'vS_IMponFa',
      'hn29V-jHIJ',
      'dCdeXa3eqQ',
      'tiK1Ehgw_S',
      'c4GlGVMhYT',
      'ZEP03E1zXW',
    ],
    linkedNodes: {},
  },
  jh2NaWuv3f: {
    type: {
      resolvedName: 'Header',
    },
    isCanvas: false,
    props: {
      imageType: 'square',
      alignItems: 'center',
      margin: [0, 0, 6, 0],
      padding: [6, 12, 6, 12],
      justifyContent: 'center',
      image: {
        show: true,
        label: 'Image',
        value: 'Image',
      },
      title: {
        value: 'YOUR NAME',
        label: 'Title',
        show: true,
      },
      subtitle: {
        value: 'The role you are applying for?',
        label: 'SubTitle',
        show: true,
      },
      fields: [
        {
          value: 'Phone',
          label: 'Phone',
          show: true,
        },
        {
          value: 'Email',
          label: 'Email',
          show: true,
        },
        {
          value: 'LinkedIn/Portfolio',
          label: 'Link',
          show: true,
        },
        {
          value: 'Extra Link',
          label: 'Extra Link',
          show: false,
        },
        {
          value: 'Location',
          label: 'Location',
          show: true,
        },
        {
          value: 'Extra Field',
          label: 'Extra Field',
          show: false,
        },
      ],
    },
    displayName: 'Header',
    custom: {},
    parent: 'rRky9FKhnD',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  ThQeX6ezUI: {
    type: {
      resolvedName: 'Summary',
    },
    isCanvas: false,
    props: {
      gap: '0px',
      margin: [0, 0, 6, 0],
      padding: [6, 12, 6, 12],
      entries: [
        {
          id: 'Entry 1',
          value: '',
        },
      ],
      title: 'Summary',
      placeholder:
        "What's the one thing that makes you the best candidate for this job?",
    },
    displayName: 'Summary',
    custom: {},
    parent: 'rRky9FKhnD',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  N_oK1Q69Z8: {
    type: {
      resolvedName: 'Experience',
    },
    isCanvas: false,
    props: {
      padding: [0],
      margin: [0, 0, 6, 0],
      gap: '0px',
      title: 'Experience',
    },
    displayName: 'Experience',
    custom: {
      toolbar: ['add', 'delete', 'setting'],
    },
    parent: 'rRky9FKhnD',
    hidden: false,
    nodes: ['OGLR7lPDwo'],
    linkedNodes: {},
  },
  dbZ6MwyAiv: {
    type: {
      resolvedName: 'Education',
    },
    isCanvas: false,
    props: {
      padding: [0],
      margin: [0, 0, 6, 0],
      gap: '0px',
      deletable: true,
      title: 'Education',
    },
    displayName: 'Education',
    custom: {
      toolbar: ['add', 'delete', 'setting'],
    },
    parent: 'rRky9FKhnD',
    hidden: false,
    nodes: ['tiZ8sfy-P9'],
    linkedNodes: {},
  },
  vS_IMponFa: {
    type: {
      resolvedName: 'Education',
    },
    isCanvas: false,
    props: {
      padding: [0],
      margin: [0, 0, 6, 0],
      gap: '0px',
      deletable: true,
      title: 'Education',
    },
    displayName: 'Education',
    custom: {
      toolbar: ['add', 'delete', 'setting'],
    },
    parent: 'rRky9FKhnD',
    hidden: false,
    nodes: ['JmbAUHe4A7'],
    linkedNodes: {},
  },
  'hn29V-jHIJ': {
    type: {
      resolvedName: 'Education',
    },
    isCanvas: false,
    props: {
      padding: [0],
      margin: [0, 0, 6, 0],
      gap: '0px',
      deletable: true,
      title: 'Education',
    },
    displayName: 'Education',
    custom: {
      toolbar: ['add', 'delete', 'setting'],
    },
    parent: 'rRky9FKhnD',
    hidden: false,
    nodes: ['YgLJfJzsr7'],
    linkedNodes: {},
  },
  dCdeXa3eqQ: {
    type: {
      resolvedName: 'Education',
    },
    isCanvas: false,
    props: {
      padding: [0],
      margin: [0, 0, 6, 0],
      gap: '0px',
      deletable: true,
      title: 'Education',
    },
    displayName: 'Education',
    custom: {
      toolbar: ['add', 'delete', 'setting'],
    },
    parent: 'rRky9FKhnD',
    hidden: false,
    nodes: ['bTA843dWmb'],
    linkedNodes: {},
  },
  tiK1Ehgw_S: {
    type: {
      resolvedName: 'Education',
    },
    isCanvas: false,
    props: {
      padding: [0],
      margin: [0, 0, 6, 0],
      gap: '0px',
      deletable: true,
      title: 'Education',
    },
    displayName: 'Education',
    custom: {
      toolbar: ['add', 'delete', 'setting'],
    },
    parent: 'rRky9FKhnD',
    hidden: false,
    nodes: ['TwN9iHO2fQ'],
    linkedNodes: {},
  },
  c4GlGVMhYT: {
    type: {
      resolvedName: 'Education',
    },
    isCanvas: false,
    props: {
      padding: [0],
      margin: [0, 0, 6, 0],
      gap: '0px',
      deletable: true,
      title: 'Education',
    },
    displayName: 'Education',
    custom: {
      toolbar: ['add', 'delete', 'setting'],
    },
    parent: 'rRky9FKhnD',
    hidden: false,
    nodes: ['9B-2jUCNMR'],
    linkedNodes: {},
  },
  OGLR7lPDwo: {
    type: {
      resolvedName: 'ExperienceEntry',
    },
    isCanvas: false,
    props: {
      entry: {
        id: 'Entry 1',
        value: '',
        companyDesc: '',
        companyName: '',
        datePeriod: '',
        location: '',
        title: '',
        hiddenField: [],
      },
      deletable: true,
      padding: [0, 12, 6, 12],
    },
    displayName: 'Experience Entry',
    custom: {
      toolbar: ['move', 'delete', 'setting'],
    },
    parent: 'N_oK1Q69Z8',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  'tiZ8sfy-P9': {
    type: {
      resolvedName: 'EducationEntry',
    },
    isCanvas: false,
    props: {
      entry: {
        id: 'Entry 1',
        value: '',
        location: '',
        schoolTitle: '',
        datePeriod: '',
        bullets: '',
        gpa: '--',
        hiddenField: ['gpa', 'location', 'bullets'],
      },
      deletable: true,
      padding: [0, 12, 6, 12],
    },
    displayName: 'Education Entry',
    custom: {
      toolbar: ['move', 'delete', 'setting'],
    },
    parent: 'dbZ6MwyAiv',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  JmbAUHe4A7: {
    type: {
      resolvedName: 'EducationEntry',
    },
    isCanvas: false,
    props: {
      entry: {
        id: 'Entry 1',
        value: '',
        location: '',
        schoolTitle: '',
        datePeriod: '',
        bullets: '',
        gpa: '--',
        hiddenField: ['gpa', 'location', 'bullets'],
      },
      deletable: true,
      padding: [0, 12, 6, 12],
    },
    displayName: 'Education Entry',
    custom: {
      toolbar: ['move', 'delete', 'setting'],
    },
    parent: 'vS_IMponFa',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  YgLJfJzsr7: {
    type: {
      resolvedName: 'EducationEntry',
    },
    isCanvas: false,
    props: {
      entry: {
        id: 'Entry 1',
        value: '',
        location: '',
        schoolTitle: '',
        datePeriod: '',
        bullets: '',
        gpa: '--',
        hiddenField: ['gpa', 'location', 'bullets'],
      },
      deletable: true,
      padding: [0, 12, 6, 12],
    },
    displayName: 'Education Entry',
    custom: {
      toolbar: ['move', 'delete', 'setting'],
    },
    parent: 'hn29V-jHIJ',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  bTA843dWmb: {
    type: {
      resolvedName: 'EducationEntry',
    },
    isCanvas: false,
    props: {
      entry: {
        id: 'Entry 1',
        value: '',
        location: '',
        schoolTitle: '',
        datePeriod: '',
        bullets: '',
        gpa: '--',
        hiddenField: ['gpa', 'location', 'bullets'],
      },
      deletable: true,
      padding: [0, 12, 6, 12],
    },
    displayName: 'Education Entry',
    custom: {
      toolbar: ['move', 'delete', 'setting'],
    },
    parent: 'dCdeXa3eqQ',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  TwN9iHO2fQ: {
    type: {
      resolvedName: 'EducationEntry',
    },
    isCanvas: false,
    props: {
      entry: {
        id: 'Entry 1',
        value: '',
        location: '',
        schoolTitle: '',
        datePeriod: '',
        bullets: '',
        gpa: '--',
        hiddenField: ['gpa', 'location', 'bullets'],
      },
      deletable: true,
      padding: [0, 12, 6, 12],
    },
    displayName: 'Education Entry',
    custom: {
      toolbar: ['move', 'delete', 'setting'],
    },
    parent: 'tiK1Ehgw_S',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  '9B-2jUCNMR': {
    type: {
      resolvedName: 'EducationEntry',
    },
    isCanvas: false,
    props: {
      entry: {
        id: 'Entry 1',
        value: '',
        location: '',
        schoolTitle: '',
        datePeriod: '',
        bullets: '',
        gpa: '--',
        hiddenField: ['gpa', 'location', 'bullets'],
      },
      deletable: true,
      padding: [0, 12, 6, 12],
    },
    displayName: 'Education Entry',
    custom: {
      toolbar: ['move', 'delete', 'setting'],
    },
    parent: 'c4GlGVMhYT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  hfxgkIIx4y: {
    type: {
      resolvedName: 'Container',
    },
    isCanvas: true,
    props: {
      padding: [44, 38, 44, 38],
      background: '#FFFFFF',
      color: '#333333',
      borderRadius: 0,
      flexDirection: 'column',
      justifyContent: 'start',
      alignItems: 'start',
      width: '100%',
      height: 'auto',
      shadow: 'md',
      resizeable: false,
      className: 'relative overflow-hidden ROOT !w-[210mm] mx-auto !h-[297mm]',
    },
    displayName: 'Container',
    custom: {
      toolbar: ['delete'],
      displayName: 'PAGE',
    },
    parent: 'ROOT',
    hidden: false,
    nodes: ['ieC4qtWz3y'],
    linkedNodes: {},
  },
  ieC4qtWz3y: {
    type: {
      resolvedName: 'Header',
    },
    isCanvas: false,
    props: {
      imageType: 'square',
      alignItems: 'center',
      margin: [0, 0, 6, 0],
      padding: [6, 12, 6, 12],
      justifyContent: 'center',
      image: {
        show: true,
        label: 'Image',
        value: 'Image',
      },
      title: {
        value: 'YOUR NAME',
        label: 'Title',
        show: true,
      },
      subtitle: {
        value: 'The role you are applying for?',
        label: 'SubTitle',
        show: true,
      },
      fields: [
        {
          value: 'Phone',
          label: 'Phone',
          show: true,
        },
        {
          value: 'Email',
          label: 'Email',
          show: true,
        },
        {
          value: 'LinkedIn/Portfolio',
          label: 'Link',
          show: true,
        },
        {
          value: 'Extra Link',
          label: 'Extra Link',
          show: false,
        },
        {
          value: 'Location',
          label: 'Location',
          show: true,
        },
        {
          value: 'Extra Field',
          label: 'Extra Field',
          show: false,
        },
      ],
    },
    displayName: 'Header',
    custom: {},
    parent: 'hfxgkIIx4y',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  ZEP03E1zXW: {
    type: {
      resolvedName: 'Container',
    },
    isCanvas: true,
    props: {
      padding: [0],
      background: 'transparent',
      color: '#333333',
      borderRadius: 0,
      flexDirection: 'column',
      justifyContent: 'start',
      alignItems: 'start',
      width: '100%',
      height: 'auto',
      resizeable: false,
    },
    displayName: 'Container',
    custom: {
      toolbar: ['delete'],
      displayName: 'EducationContainer',
    },
    parent: 'rRky9FKhnD',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
};
